# Generated by Django 4.1.7 on 2023-03-10 18:22

from django.db import migrations, models
import phonenumber_field.modelfields
import visitors.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=128)),
                ('first_names', models.CharField(max_length=555)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('card_image', models.ImageField(blank=True, null=True, upload_to=visitors.models.image_dir_path)),
                ('email', models.EmailField(blank=True, default='hub@test.com', max_length=128)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('sex', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
