# Generated by Django 4.1.7 on 2023-03-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.EmailField(blank=True, default='hub@test.com', max_length=128, null=True),
        ),
    ]
