# Generated by Django 4.1.7 on 2023-03-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_alter_visitor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
