# Generated by Django 4.1.7 on 2023-03-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_alter_visitor_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='card_image',
            field=models.FileField(default='images/None/No-img.jpg', upload_to='images/'),
        ),
    ]
