# Generated by Django 4.1.7 on 2023-03-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_alter_visitor_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='card_image',
            field=models.FileField(blank=True, default='images/None/No-img.jpg', null=True, upload_to='images/'),
        ),
    ]
