# Generated by Django 4.1.7 on 2023-03-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0006_alter_visitor_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='card_image',
            field=models.CharField(max_length=555, unique=True),
        ),
    ]
